// app/lib/searchAliases.js
// GENERATED by scripts/gen-aliases.mjs — do not hand-edit. Add entries to the
// SOURCE lists instead (fikstur-app/lib/i18n.js TEAM_NAMES, app/lib/popular.js)
// and re-run the generator.
//
// What this is FOR, and what it is NOT:
// It is a CLUB name dictionary — translations ("İngiltere" = England), nicknames
// ("cimbom" = Galatasaray) and short forms ("bjk") that no data provider ships.
// Clubs only: personal names are not unique enough to match on safely.
// It is NOT the ranking engine: ranking lives in search_all() in Postgres, and
// popularity is derived from league tier at seed time. `boost` is only a FLOOR
// for a handful of globally famous names whose league tier understates them
// (Inter Miami in MLS, Al Nassr in the Saudi league). Everything still works with
// this file empty — it just makes Turkish and nickname queries land better.

export const SEARCH_ALIASES = {
  "teams": {
    "1. FC Köln": {
      "a": [
        "Colonia",
        "Köln"
      ],
      "boost": null
    },
    "AC Milan": {
      "a": [
        "AC Mailand",
        "Milan",
        "acmilan",
        "milan"
      ],
      "boost": 97
    },
    "Adana Demirspor": {
      "a": [
        "adana"
      ],
      "boost": 66
    },
    "Ajax": {
      "a": [],
      "boost": 85
    },
    "Al Hilal": {
      "a": [
        "al-hilal",
        "alhilal"
      ],
      "boost": 84
    },
    "Al Nassr": {
      "a": [
        "al-nassr",
        "alnassr"
      ],
      "boost": 90
    },
    "Algeria": {
      "a": [
        "Algerien",
        "Argelia",
        "Cezayir"
      ],
      "boost": null
    },
    "Argentina": {
      "a": [
        "Argentinien",
        "Arjantin",
        "arjantin"
      ],
      "boost": 96
    },
    "Arsenal": {
      "a": [],
      "boost": 97
    },
    "Aston Villa": {
      "a": [
        "villa"
      ],
      "boost": 82
    },
    "Athletic Club": {
      "a": [
        "athletic",
        "athletic bilbao"
      ],
      "boost": 78
    },
    "Atletico Madrid": {
      "a": [
        "Atlético Madrid",
        "Atlético de Madrid",
        "atleti",
        "atletico"
      ],
      "boost": 93
    },
    "Australia": {
      "a": [
        "Australien",
        "Avustralya"
      ],
      "boost": null
    },
    "Austria": {
      "a": [
        "Avusturya",
        "avusturya",
        "Österreich"
      ],
      "boost": 72
    },
    "Barcelona": {
      "a": [
        "barca",
        "barsa",
        "fc barcelona"
      ],
      "boost": 100
    },
    "Basaksehir": {
      "a": [
        "Başakşehir",
        "istanbul basaksehir"
      ],
      "boost": 72
    },
    "Bayer Leverkusen": {
      "a": [
        "bayer",
        "leverkusen"
      ],
      "boost": 86
    },
    "Bayern Munich": {
      "a": [
        "Bayern Monaco",
        "Bayern Múnich",
        "Bayern München",
        "Bayern Münih"
      ],
      "boost": null
    },
    "Bayern München": {
      "a": [
        "Bayern Monaco",
        "Bayern Múnich",
        "Bayern Münih",
        "bayern",
        "bayern munchen",
        "bayern munih",
        "munih",
        "münih"
      ],
      "boost": 98
    },
    "Belgium": {
      "a": [
        "Belgien",
        "Belgio",
        "Belçika",
        "Bélgica",
        "belcika"
      ],
      "boost": 86
    },
    "Benfica": {
      "a": [
        "Benfica Lissabon"
      ],
      "boost": 84
    },
    "Besiktas": {
      "a": [
        "Beşiktaş",
        "bjk",
        "kartal"
      ],
      "boost": 93
    },
    "Boca Juniors": {
      "a": [
        "boca"
      ],
      "boost": 84
    },
    "Bodrumspor": {
      "a": [],
      "boost": null
    },
    "Borussia Dortmund": {
      "a": [
        "bvb",
        "dortmund"
      ],
      "boost": 94
    },
    "Borussia Mönchengladbach": {
      "a": [],
      "boost": null
    },
    "Brazil": {
      "a": [
        "Brasil",
        "Brasile",
        "Brasilien",
        "Brezilya",
        "brasil",
        "brezilya"
      ],
      "boost": 96
    },
    "Cameroon": {
      "a": [
        "Camerun",
        "Camerún",
        "Kamerun"
      ],
      "boost": null
    },
    "Canada": {
      "a": [
        "Canadá",
        "Kanada"
      ],
      "boost": null
    },
    "Caykur Rizespor": {
      "a": [
        "Çaykur Rizespor"
      ],
      "boost": null
    },
    "Celtic": {
      "a": [],
      "boost": 78
    },
    "Chelsea": {
      "a": [],
      "boost": 97
    },
    "Chile": {
      "a": [
        "Cile",
        "Şili"
      ],
      "boost": null
    },
    "Colombia": {
      "a": [
        "Kolombiya",
        "Kolumbien",
        "kolombiya"
      ],
      "boost": 76
    },
    "Costa Rica": {
      "a": [
        "Kosta Rika"
      ],
      "boost": null
    },
    "Croatia": {
      "a": [
        "Croacia",
        "Croazia",
        "Hırvatistan",
        "Kroatien",
        "hirvatistan"
      ],
      "boost": 85
    },
    "Czech Republic": {
      "a": [
        "Chequia",
        "Repubblica Ceca",
        "Tschechien",
        "Çekya"
      ],
      "boost": null
    },
    "Czechia": {
      "a": [
        "Chequia",
        "Repubblica Ceca",
        "Tschechien",
        "Çekya"
      ],
      "boost": null
    },
    "Denmark": {
      "a": [
        "Danimarca",
        "Danimarka",
        "Dinamarca",
        "Dänemark",
        "danimarka"
      ],
      "boost": 76
    },
    "Ecuador": {
      "a": [
        "Ekvador"
      ],
      "boost": null
    },
    "Egypt": {
      "a": [
        "Egipto",
        "Egitto",
        "Mısır",
        "misir",
        "Ägypten"
      ],
      "boost": 76
    },
    "England": {
      "a": [
        "Inghilterra",
        "Inglaterra",
        "ingiltere",
        "İngiltere"
      ],
      "boost": 95
    },
    "Everton": {
      "a": [],
      "boost": 76
    },
    "Eyupspor": {
      "a": [
        "Eyüpspor"
      ],
      "boost": null
    },
    "FC Koln": {
      "a": [
        "1. FC Köln",
        "Colonia",
        "Köln"
      ],
      "boost": null
    },
    "FC Porto": {
      "a": [
        "porto"
      ],
      "boost": 84
    },
    "Fenerbahce": {
      "a": [
        "Fenerbahçe",
        "fb",
        "fener"
      ],
      "boost": 96
    },
    "Feyenoord": {
      "a": [],
      "boost": 76
    },
    "Flamengo": {
      "a": [],
      "boost": 82
    },
    "France": {
      "a": [
        "Francia",
        "Frankreich",
        "Fransa",
        "fransa"
      ],
      "boost": 95
    },
    "Galatasaray": {
      "a": [
        "cimbom",
        "gala",
        "gs"
      ],
      "boost": 96
    },
    "Gaziantep FK": {
      "a": [
        "Gaziantep"
      ],
      "boost": null
    },
    "Germany": {
      "a": [
        "Alemania",
        "Almanya",
        "Deutschland",
        "Germania",
        "almanya"
      ],
      "boost": 95
    },
    "Ghana": {
      "a": [
        "Gana"
      ],
      "boost": null
    },
    "Goztepe": {
      "a": [
        "Göztepe"
      ],
      "boost": null
    },
    "Greece": {
      "a": [
        "Grecia",
        "Griechenland",
        "Yunanistan",
        "yunanistan"
      ],
      "boost": 72
    },
    "Hungary": {
      "a": [
        "Hungría",
        "Macaristan",
        "Ungarn",
        "Ungheria"
      ],
      "boost": null
    },
    "Inter": {
      "a": [
        "Inter Mailand",
        "Inter de Milán",
        "inter milan",
        "internazionale"
      ],
      "boost": 96
    },
    "Inter Miami": {
      "a": [
        "miami"
      ],
      "boost": 86
    },
    "Iran": {
      "a": [
        "Irán",
        "İran"
      ],
      "boost": null
    },
    "Ireland": {
      "a": [
        "Irland",
        "Irlanda",
        "İrlanda"
      ],
      "boost": null
    },
    "Istanbul Basaksehir": {
      "a": [
        "Estambul Basaksehir",
        "İstanbul Başakşehir"
      ],
      "boost": null
    },
    "Italy": {
      "a": [
        "Italia",
        "Italien",
        "italia",
        "italya",
        "İtalya"
      ],
      "boost": 93
    },
    "Ivory Coast": {
      "a": [
        "Costa d'Avorio",
        "Costa de Marfil",
        "Elfenbeinküste",
        "Fildişi Sahili"
      ],
      "boost": null
    },
    "Japan": {
      "a": [
        "Giappone",
        "Japonya",
        "Japón",
        "japonya"
      ],
      "boost": 78
    },
    "Juventus": {
      "a": [
        "Juventus Turin",
        "juve"
      ],
      "boost": 97
    },
    "Kasimpasa": {
      "a": [
        "Kasımpaşa"
      ],
      "boost": null
    },
    "Korea Republic": {
      "a": [
        "Corea del Sud",
        "Corea del Sur",
        "Güney Kore",
        "Südkorea"
      ],
      "boost": null
    },
    "Lazio": {
      "a": [],
      "boost": 82
    },
    "Liverpool": {
      "a": [],
      "boost": 98
    },
    "Manchester City": {
      "a": [
        "city",
        "man city"
      ],
      "boost": 99
    },
    "Manchester United": {
      "a": [
        "man united",
        "man utd",
        "manu",
        "united"
      ],
      "boost": 99
    },
    "Marseille": {
      "a": [
        "om"
      ],
      "boost": 80
    },
    "Mexico": {
      "a": [
        "Meksika",
        "Messico",
        "Mexiko",
        "México",
        "meksika"
      ],
      "boost": 80
    },
    "Monaco": {
      "a": [
        "as monaco"
      ],
      "boost": 76
    },
    "Morocco": {
      "a": [
        "Fas",
        "Marocco",
        "Marokko",
        "Marruecos",
        "fas"
      ],
      "boost": 84
    },
    "Napoli": {
      "a": [],
      "boost": 90
    },
    "Netherlands": {
      "a": [
        "Hollanda",
        "Niederlande",
        "Paesi Bassi",
        "Países Bajos",
        "holland",
        "hollanda"
      ],
      "boost": 92
    },
    "New Zealand": {
      "a": [
        "Neuseeland",
        "Nueva Zelanda",
        "Nuova Zelanda",
        "Yeni Zelanda"
      ],
      "boost": null
    },
    "Newcastle": {
      "a": [
        "newcastle united"
      ],
      "boost": 85
    },
    "Nigeria": {
      "a": [
        "Nijerya",
        "nijerya"
      ],
      "boost": 76
    },
    "Norway": {
      "a": [
        "Noruega",
        "Norvegia",
        "Norveç",
        "Norwegen"
      ],
      "boost": null
    },
    "Olympique Lyonnais": {
      "a": [
        "lyon",
        "ol"
      ],
      "boost": 78
    },
    "PSV Eindhoven": {
      "a": [
        "PSV",
        "psv"
      ],
      "boost": 78
    },
    "Palmeiras": {
      "a": [],
      "boost": 78
    },
    "Paraguay": {
      "a": [],
      "boost": null
    },
    "Paris Saint Germain": {
      "a": [
        "paris",
        "psg"
      ],
      "boost": 98
    },
    "Peru": {
      "a": [
        "Perù",
        "Perú"
      ],
      "boost": null
    },
    "Poland": {
      "a": [
        "Polen",
        "Polonia",
        "Polonya",
        "polonya"
      ],
      "boost": 78
    },
    "Portugal": {
      "a": [
        "Portekiz",
        "Portogallo",
        "portekiz"
      ],
      "boost": 94
    },
    "Qatar": {
      "a": [
        "Catar",
        "Katar"
      ],
      "boost": null
    },
    "RB Leipzig": {
      "a": [
        "leipzig"
      ],
      "boost": 82
    },
    "Rangers": {
      "a": [
        "glasgow rangers"
      ],
      "boost": 76
    },
    "Real Betis": {
      "a": [
        "betis"
      ],
      "boost": 78
    },
    "Real Madrid": {
      "a": [
        "real"
      ],
      "boost": 100
    },
    "Real Sociedad": {
      "a": [
        "sociedad"
      ],
      "boost": 78
    },
    "River Plate": {
      "a": [
        "river"
      ],
      "boost": 84
    },
    "Rizespor": {
      "a": [],
      "boost": null
    },
    "Roma": {
      "a": [
        "as roma"
      ],
      "boost": 87
    },
    "Romania": {
      "a": [
        "Romanya",
        "Rumanía",
        "Rumänien"
      ],
      "boost": null
    },
    "Russia": {
      "a": [
        "Rusia",
        "Russland",
        "Rusya"
      ],
      "boost": null
    },
    "Samsunspor": {
      "a": [
        "samsun"
      ],
      "boost": 63
    },
    "Saudi Arabia": {
      "a": [
        "Arabia Saudita",
        "Saudi-Arabien",
        "Suudi Arabistan"
      ],
      "boost": null
    },
    "Scotland": {
      "a": [
        "Escocia",
        "Schottland",
        "Scozia",
        "iskocya",
        "İskoçya"
      ],
      "boost": 72
    },
    "Senegal": {
      "a": [],
      "boost": 76
    },
    "Serbia": {
      "a": [
        "Serbien",
        "Sırbistan",
        "sirbistan"
      ],
      "boost": 76
    },
    "Sevilla": {
      "a": [],
      "boost": 82
    },
    "South Africa": {
      "a": [
        "Güney Afrika",
        "Sudafrica",
        "Sudáfrica",
        "Südafrika"
      ],
      "boost": null
    },
    "South Korea": {
      "a": [
        "Corea del Sud",
        "Corea del Sur",
        "Güney Kore",
        "Südkorea",
        "guney kore",
        "kore"
      ],
      "boost": 76
    },
    "Spain": {
      "a": [
        "España",
        "Spagna",
        "Spanien",
        "espana",
        "ispanya",
        "İspanya"
      ],
      "boost": 95
    },
    "Sporting CP": {
      "a": [
        "Sporting Lisbona",
        "Sporting Lissabon",
        "Sporting Lizbon",
        "Sporting de Lisboa",
        "sporting",
        "sporting lisbon"
      ],
      "boost": 82
    },
    "Sporting Lisbon": {
      "a": [
        "Sporting Lisbona",
        "Sporting Lissabon",
        "Sporting Lizbon",
        "Sporting de Lisboa"
      ],
      "boost": null
    },
    "Sweden": {
      "a": [
        "Schweden",
        "Suecia",
        "Svezia",
        "isvec",
        "İsveç"
      ],
      "boost": 74
    },
    "Switzerland": {
      "a": [
        "Schweiz",
        "Suiza",
        "Svizzera",
        "isvicre",
        "İsviçre"
      ],
      "boost": 74
    },
    "Tottenham": {
      "a": [
        "hotspur",
        "spurs"
      ],
      "boost": 92
    },
    "Trabzonspor": {
      "a": [
        "trabzon",
        "ts"
      ],
      "boost": 88
    },
    "Tunisia": {
      "a": [
        "Tunesien",
        "Tunus",
        "Túnez"
      ],
      "boost": null
    },
    "Turkey": {
      "a": [
        "Turchia",
        "Turquía",
        "Türkei",
        "Türkiye",
        "ay yildizlilar",
        "milli takim",
        "turkiye"
      ],
      "boost": 92
    },
    "Türkiye": {
      "a": [
        "Turchia",
        "Turquía",
        "Türkei"
      ],
      "boost": null
    },
    "USA": {
      "a": [
        "ABD",
        "EE. UU.",
        "abd",
        "amerika",
        "united states"
      ],
      "boost": 78
    },
    "Ukraine": {
      "a": [
        "Ucraina",
        "Ucrania",
        "Ukrayna"
      ],
      "boost": null
    },
    "United States": {
      "a": [
        "ABD",
        "Estados Unidos",
        "Stati Uniti",
        "USA"
      ],
      "boost": null
    },
    "Uruguay": {
      "a": [],
      "boost": 84
    },
    "Valencia": {
      "a": [],
      "boost": 80
    },
    "Villarreal": {
      "a": [],
      "boost": 78
    },
    "Wales": {
      "a": [
        "Gales",
        "Galler",
        "Galles",
        "galler"
      ],
      "boost": 70
    },
    "West Ham": {
      "a": [
        "west ham united"
      ],
      "boost": 78
    }
  }
};

// canonical club name -> { a: string[] aliases, boost: number|null }
export function aliasesFor(name) {
  return SEARCH_ALIASES.teams[name] || null;
}
