// scripts/gen-aliases.mjs
// Regenerates app/lib/searchAliases.js from the two name dictionaries we already
// maintain by hand:
//   1. fikstur-app/lib/i18n.js  TEAM_NAMES  — UI localisation (tr/de/es/it)
//   2. app/lib/popular.js       POP_TEAMS / POP_PLAYERS — nicknames + short forms
//
// Both were written for other purposes; this folds them into one alias table that
// the search seeder attaches to indexed entities, so "İngiltere", "cimbom" and
// "bjk" resolve without any of it living in the ranking path.
//
//   node scripts/gen-aliases.mjs [--app-repo ../fikstur-app]
//
// Safe to re-run: output is deterministic (sorted), so a no-change run produces
// no diff.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..");

const argOf = (flag, fallback) => {
  const i = process.argv.indexOf(flag);
  return i > -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
};
const APP_REPO = path.resolve(ROOT, argOf("--app-repo", "../fikstur-app"));
const OUT = path.join(ROOT, "app", "lib", "searchAliases.js");

const i18nPath = path.join(APP_REPO, "lib", "i18n.js");
if (!fs.existsSync(i18nPath)) {
  console.error(`i18n.js not found at ${i18nPath} — pass --app-repo <path to fikstur-app>`);
  process.exit(1);
}

const i18n = await import(pathToFileURL(i18nPath).href);
const popular = await import(pathToFileURL(path.join(ROOT, "app", "lib", "popular.js")).href);

const teams = new Map(); // canonical (API-Football English) name -> { a: Set, boost: number|null }
const ensure = (m, k) => {
  if (!m.has(k)) m.set(k, { a: new Set(), boost: null });
  return m.get(k);
};
const put = (m, canon, alias) => {
  if (!canon || !alias) return;
  const s = String(alias).trim();
  if (s && s.toLowerCase() !== canon.toLowerCase()) ensure(m, canon).a.add(s);
};

for (const [canon, locales] of Object.entries(i18n.TEAM_NAMES || {})) {
  ensure(teams, canon);
  for (const localised of Object.values(locales)) put(teams, canon, localised);
}
for (const e of popular.POP_TEAMS || []) {
  const rec = ensure(teams, e.en);
  (e.a || []).forEach((x) => put(teams, e.en, x));
  rec.boost = e.pop ?? null;
}

// POP_PLAYERS is deliberately NOT emitted. Its keys are surnames ("Vinicius",
// "Son", "Rodri", "Yildiz"), and a surname does not identify a person — matching
// players against it by name gave Vinícius Júnior's nicknames and fame rating to
// an unrelated Vinicius at RB Bragantino. Player popularity comes from the club.

const serialise = (m) =>
  Object.fromEntries(
    [...m.entries()]
      .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
      .map(([k, v]) => [k, { a: [...v.a].sort(), boost: v.boost }])
  );

const payload = { teams: serialise(teams) };

const header = `// app/lib/searchAliases.js
// GENERATED by scripts/gen-aliases.mjs — do not hand-edit. Add entries to the
// SOURCE lists instead (fikstur-app/lib/i18n.js TEAM_NAMES, app/lib/popular.js)
// and re-run the generator.
//
// What this is FOR, and what it is NOT:
// It is a CLUB name dictionary — translations ("İngiltere" = England), nicknames
// ("cimbom" = Galatasaray) and short forms ("bjk") that no data provider ships.
// Clubs only: personal names are not unique enough to match on safely.
// It is NOT the ranking engine: ranking lives in search_all() in Postgres, and
// popularity is derived from league tier at seed time. \`boost\` is only a FLOOR
// for a handful of globally famous names whose league tier understates them
// (Inter Miami in MLS, Al Nassr in the Saudi league). Everything still works with
// this file empty — it just makes Turkish and nickname queries land better.
`;

const body = `${header}
export const SEARCH_ALIASES = ${JSON.stringify(payload, null, 2)};

// canonical club name -> { a: string[] aliases, boost: number|null }
export function aliasesFor(name) {
  return SEARCH_ALIASES.teams[name] || null;
}
`;

fs.writeFileSync(OUT, body);
console.log(
  `wrote ${path.relative(ROOT, OUT)} — ${Object.keys(payload.teams).length} clubs`
);
